apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  namespace: web
  labels:
    app: tripviewer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer-app
  template:
    metadata:
      labels:
        app: tripviewer-app
    spec:
      containers:
      - name: tripviewer-app
        image: registryqjy5952.azurecr.io/tripviewer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: USERPROFILE_API_ENDPOINT
            value: userprofile.api.svc
          - name: TRIPS_API_ENDPOINT
            value: trip.api.svc
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 512Mi
