apiVersion: v1
kind: Service
metadata:
  namespace: api
  name: trips
  labels:
    app: trips
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: trips-service