apiVersion: v1
kind: Service
metadata:
  namespace: web
  name: tripviewer
  labels:
    app: tripviewer
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: tripviewer-app
