apiVersion: v1
kind: Service
metadata:
  namespace: api
  name: user
  labels:
    app: user
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: user-service